repos:
  # Tama√±os de archivo
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=5000']
      - id: check-csv

  # Gitleaks (no-bloqueante)
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.1
    hooks:
      - id: gitleaks
        stages: [commit]
        verbose: true